name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.1]
        
    steps:
      - name: Install node dependencies
        run: npm install
      - name: Deploy front-end
        run: |
          cd phishingidentify &&
          npm start &
      - name: Test React App
        run: cd phishingidentify && npm run test:e2e
    
  deploy:
    if: ${{github.ref == 'refs/heads/main'}}
    name: Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "phishing-alert-frontend"
          heroku_email: "phishingidentify@gmail.com"
          appdir: "phishingidentify/"
